version: '3.7'
services:
    web:
        image: nginx:latest
        container_name: nginx8008
        ports:
            - "8008:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - /data/docker_volumes/php/app:/app
    mysql:
        image: mysql:5.7
        container_name: mysql-server-57
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_HOST: '%' # allow login from any IP, needs to be enclosed with quotes
          MYSQL_ROOT_PASSWORD: r00t
          MYSQL_DATABASE: 'demo'
          MYSQL_USER: 'hynial'
          MYSQL_PASSWORD: 'hynial'
          MYSQL_TCP_PORT: 13307
        ports:
            - '13307:13307'
        expose:
            - "13307"
        volumes:
            - /data/docker_volumes/php/mysql:/var/lib/mysql # the direcotry should be empty or db will not created.
            - ./docker.cnf:/etc/mysql/conf.d/docker.cnf
            - ./init:/docker-entrypoint-initdb.d # must be a directory. All the .sql's in the directory will be imported.
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        container_name: php9000
        volumes:
            - /data/docker_volumes/php/app:/app
        depends_on:
            - mysql